# Generated by Django 3.2.2 on 2021-05-07 08:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import froala_editor.fields
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LXMB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MBID', models.IntegerField(verbose_name='模板ID')),
                ('MBNR', froala_editor.fields.FroalaField(verbose_name='模板内容')),
                ('BZXX', models.CharField(max_length=255, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '票件类型模板',
                'verbose_name_plural': '票件类型模板',
                'db_table': 'OA_VS_LXMB',
            },
        ),
        migrations.CreateModel(
            name='tongji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TPSJ', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投票日期')),
            ],
            options={
                'verbose_name': '投票统计',
                'verbose_name_plural': '投票统计',
                'db_table': 'OA_VS_tj',
            },
        ),
        migrations.CreateModel(
            name='tongjiCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COUNT', models.IntegerField(default=0, verbose_name='投票次数')),
            ],
            options={
                'verbose_name': '投票统计_数量统计',
                'verbose_name_plural': '投票统计_数量统计',
                'db_table': 'OA_VS_tj_count',
            },
        ),
        migrations.CreateModel(
            name='TPXM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XMID', models.IntegerField(verbose_name='票件项目ID')),
                ('XMMC', models.CharField(max_length=255, verbose_name='票件项目名称')),
                ('CJRQ', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
            ],
            options={
                'verbose_name': '投票项目',
                'verbose_name_plural': '投票项目',
                'db_table': 'OA_VS_XM',
            },
        ),
        migrations.CreateModel(
            name='XMLX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LXID', models.IntegerField(verbose_name='票件类型ID')),
                ('LXMC', models.CharField(max_length=255, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '项目类型字典',
                'verbose_name_plural': '项目类型字典',
                'db_table': 'OA_VS_ZD_XMLX',
            },
        ),
        migrations.CreateModel(
            name='XMZTZD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZTID', models.IntegerField(verbose_name='票件项目ID')),
                ('ZTMC', models.CharField(max_length=255, verbose_name='状态名称')),
            ],
            options={
                'verbose_name': '项目状态字典',
                'verbose_name_plural': '项目状态字典',
                'db_table': 'OA_VS_ZD_XMZT',
            },
        ),
        migrations.CreateModel(
            name='XXSJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XXID', models.IntegerField(verbose_name='选项ID')),
                ('XXSJ', mdeditor.fields.MDTextField(verbose_name='选项内容')),
            ],
            options={
                'verbose_name': '选项数据',
                'verbose_name_plural': '选项数据',
                'db_table': 'OA_VS_XXSJ',
            },
        ),
        migrations.CreateModel(
            name='XMZT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XMID', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='TouPiaoXiTong.tpxm', verbose_name='票件项目ID')),
                ('XMZT', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='TouPiaoXiTong.xmztzd', verbose_name='票件项目状态')),
            ],
            options={
                'verbose_name': '项目状态',
                'verbose_name_plural': '项目状态',
                'db_table': 'OA_VS_XMZT',
            },
        ),
        migrations.CreateModel(
            name='XMSJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SJID', models.IntegerField(verbose_name='数据ID')),
                ('WT', mdeditor.fields.MDTextField(verbose_name='问题内容')),
                ('XXID', models.ManyToManyField(help_text='对应的选项ID', to='TouPiaoXiTong.XXSJ', verbose_name='选项ID')),
            ],
            options={
                'verbose_name': '项目数据',
                'verbose_name_plural': '项目数据',
                'db_table': 'OA_VS_XMSJ',
            },
        ),
    ]
