# Generated by Django 3.1.7 on 2021-04-21 03:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import froala_editor.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('user', '0003_bankaccount_bankdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPXM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XMID', models.IntegerField(verbose_name='票件项目ID')),
                ('XMMC', models.CharField(max_length=255, verbose_name='票件项目名称')),
                ('CJRQ', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('CJR', models.OneToOneField(help_text='选择创建人', on_delete=django.db.models.deletion.DO_NOTHING,
                                             to='user.bankaccount', verbose_name='创建人账号')),
                ('CYR', models.ManyToManyField(help_text='选择可以参与投票的人', to='user.BankDepartment', verbose_name='参与人员')),
            ],
            options={
                'verbose_name': '投票项目',
                'verbose_name_plural': '投票项目',
                'db_table': 'OA_VS_XM',
            },
        ),
        migrations.CreateModel(
            name='XMLX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LXID', models.IntegerField(verbose_name='票件类型ID')),
                ('LXMC', models.CharField(max_length=255, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '项目类型字典',
                'verbose_name_plural': '项目类型字典',
                'db_table': 'OA_VS_ZD_XMLX',
            },
        ),
        migrations.CreateModel(
            name='XMZTZD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZTID', models.IntegerField(verbose_name='票件项目ID')),
                ('ZTMC', models.CharField(max_length=255, verbose_name='状态名称')),
            ],
            options={
                'verbose_name': '项目状态字典',
                'verbose_name_plural': '项目状态字典',
                'db_table': 'OA_VS_ZD_XMZT',
            },
        ),
        migrations.CreateModel(
            name='XXSJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XXID', models.IntegerField(verbose_name='选项ID')),
                ('XXSJ', models.FloatField(verbose_name='选项内容')),
            ],
            options={
                'verbose_name': '选项数据',
                'verbose_name_plural': '选项数据',
                'db_table': 'OA_VS_XXSJ',
            },
        ),
        migrations.CreateModel(
            name='XMZT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XMID', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='TouPiaoXiTong.tpxm',
                                              verbose_name='票件项目ID')),
                ('XMZT', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='TouPiaoXiTong.xmztzd',
                                              verbose_name='票件项目状态')),
            ],
            options={
                'verbose_name': '项目状态',
                'verbose_name_plural': '项目状态',
                'db_table': 'OA_VS_XMZT',
            },
        ),
        migrations.CreateModel(
            name='XMSJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SJID', models.IntegerField(verbose_name='数据ID')),
                ('WT', models.FloatField(verbose_name='问题内容')),
                ('XXID', models.ManyToManyField(help_text='对应的选项ID', to='TouPiaoXiTong.XXSJ', verbose_name='选项ID')),
            ],
            options={
                'verbose_name': '项目数据',
                'verbose_name_plural': '项目数据',
                'db_table': 'OA_VS_XMSJ',
            },
        ),
        migrations.AddField(
            model_name='tpxm',
            name='SJID',
            field=models.ManyToManyField(help_text='与问题数据进行对接', to='TouPiaoXiTong.XMSJ', verbose_name='投票内容'),
        ),
        migrations.AddField(
            model_name='tpxm',
            name='XMLX',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='TouPiaoXiTong.xmlx',
                                       verbose_name='票件类型'),
        ),
        migrations.CreateModel(
            name='LXMB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MBID', models.IntegerField(verbose_name='模板ID')),
                ('MBNR', froala_editor.fields.FroalaField(verbose_name='模板代码')),
                ('BZXX', models.CharField(max_length=255, verbose_name='备注信息')),
                ('LXID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TouPiaoXiTong.xmlx',
                                           verbose_name='投票类型ID')),
            ],
            options={
                'verbose_name': '票件类型模板',
                'verbose_name_plural': '票件类型模板',
                'db_table': 'OA_VS_LXMB',
            },
        ),
    ]
