# Generated by Django 3.1.7 on 2021-04-24 04:02

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0004_auto_20210421_1508'),
        ('TouPiaoXiTong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lxmb',
            name='MBNR',
            field=froala_editor.fields.FroalaField(verbose_name='模板内容'),
        ),
        migrations.AlterField(
            model_name='tpxm',
            name='CJR',
            field=models.ForeignKey(help_text='选择创建人', on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='user.bankaccount', verbose_name='创建人账号'),
        ),
        migrations.AlterField(
            model_name='tpxm',
            name='XMLX',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TouPiaoXiTong.xmlx',
                                    verbose_name='票件类型'),
        ),
    ]
