# Generated by Django 3.1.7 on 2021-04-21 03:47

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):
    dependencies = [
        ('TouPiaoXiTong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmsj',
            name='WT',
            field=froala_editor.fields.FroalaField(verbose_name='问题内容'),
        ),
        migrations.AlterField(
            model_name='xxsj',
            name='XXSJ',
            field=froala_editor.fields.FroalaField(verbose_name='选项内容'),
        ),
    ]
