# Generated by Django 3.2.2 on 2021-05-07 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('TouPiaoXiTong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpxm',
            name='CJR',
            field=models.ForeignKey(help_text='选择创建人', on_delete=django.db.models.deletion.DO_NOTHING, to='user.bankaccount', verbose_name='创建人账号'),
        ),
        migrations.AddField(
            model_name='tpxm',
            name='CYR',
            field=models.ManyToManyField(help_text='选择可以参与投票的人', to='user.BankDepartment', verbose_name='参与人员'),
        ),
        migrations.AddField(
            model_name='tpxm',
            name='SJID',
            field=models.ForeignKey(help_text='与问题数据进行对接', on_delete=django.db.models.deletion.DO_NOTHING, to='TouPiaoXiTong.xmsj', verbose_name='投票内容'),
        ),
        migrations.AddField(
            model_name='tpxm',
            name='XMLX',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TouPiaoXiTong.xmlx', verbose_name='票件类型'),
        ),
        migrations.AddField(
            model_name='tongjicount',
            name='XXID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TouPiaoXiTong.xxsj', verbose_name='选项ID'),
        ),
        migrations.AddField(
            model_name='tongji',
            name='TPR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.bankaccount', verbose_name='投票人'),
        ),
        migrations.AddField(
            model_name='tongji',
            name='XXID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TouPiaoXiTong.xxsj', verbose_name='选项ID'),
        ),
        migrations.AddField(
            model_name='lxmb',
            name='LXID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TouPiaoXiTong.xmlx', verbose_name='投票类型ID'),
        ),
    ]
