# Generated by Django 3.1.7 on 2021-04-27 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('TouPiaoXiTong', '0002_auto_20210424_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tongji',
            name='TPSJ',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投票日期'),
        ),
    ]
