# Generated by Django 3.1.7 on 2021-04-21 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0004_auto_20210421_1508'),
        ('TouPiaoXiTong', '0002_auto_20210421_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='tongji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TPSJ', models.DateTimeField(verbose_name='投票日期')),
                ('TPR', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='user.bankaccount',
                                             verbose_name='投票人')),
                ('XXID', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='TouPiaoXiTong.xxsj',
                                              verbose_name='选项ID')),
            ],
            options={
                'verbose_name': '投票统计',
                'verbose_name_plural': '投票统计',
                'db_table': 'OA_VS_tj',
            },
        ),
    ]
