# Generated by Django 3.1.7 on 2021-04-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0004_auto_20210421_1508'),
        ('TouPiaoXiTong', '0003_tongji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tongji',
            name='TPR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.bankaccount',
                                    verbose_name='投票人'),
        ),
        migrations.AlterField(
            model_name='tongji',
            name='XXID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TouPiaoXiTong.xxsj',
                                    verbose_name='选项ID'),
        ),
    ]
