# Generated by Django 3.1.7 on 2021-04-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('TouPiaoXiTong', '0004_auto_20210421_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='tongjiCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COUNT', models.IntegerField(verbose_name='投票次数')),
                ('XXID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TouPiaoXiTong.xxsj',
                                           verbose_name='选项ID')),
            ],
            options={
                'verbose_name': '投票统计_数量统计',
                'verbose_name_plural': '投票统计_数量统计',
                'db_table': 'OA_VS_tj_count',
            },
        ),
    ]
