# Generated by Django 3.1.7 on 2021-04-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('TouPiaoXiTong', '0005_tongjicount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tongjicount',
            name='COUNT',
            field=models.IntegerField(default=0, verbose_name='投票次数'),
        ),
    ]
