# Generated by Django 3.2.2 on 2021-05-07 08:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orcl_cz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czbm', models.CharField(max_length=255, verbose_name='操作编码')),
                ('czmc', models.CharField(max_length=255, verbose_name='操作名称')),
                ('sysm', models.CharField(max_length=255, verbose_name='使用说明')),
                ('isDanger', models.CharField(max_length=255, verbose_name='操作是否危险')),
                ('sql', models.CharField(max_length=255, verbose_name='SQL语句')),
                ('bmc', models.CharField(max_length=255, verbose_name='要查询的表名称')),
                ('zd', models.CharField(max_length=255, verbose_name='要查询的字段')),
                ('imgURL', models.CharField(max_length=255, verbose_name='图片地址')),
            ],
            options={
                'verbose_name': '操作信息',
                'verbose_name_plural': '操作信息',
                'db_table': 'orcl_cz',
            },
        ),
        migrations.CreateModel(
            name='orcl_ljcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, verbose_name='IP地址')),
                ('port', models.CharField(max_length=255, verbose_name='端口号')),
                ('serverName', models.CharField(max_length=255, verbose_name='数据库名称')),
                ('username', models.CharField(max_length=255, verbose_name='数据库登陆账号')),
                ('password', models.CharField(max_length=255, verbose_name='数据库登陆密码')),
                ('mc', models.CharField(max_length=255, verbose_name='服务器名称')),
            ],
            options={
                'verbose_name': '数据库连接参数',
                'verbose_name_plural': '数据库连接参数',
                'db_table': 'orcl_ljcs',
            },
        ),
        migrations.CreateModel(
            name='orcl_cz_ls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, verbose_name='操作人IP地址')),
                ('czsj', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('isSuccess', models.CharField(max_length=255, verbose_name='是否成功操作')),
                ('czbm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orcl.orcl_cz', verbose_name='操作编码')),
            ],
            options={
                'verbose_name': '操作历史',
                'verbose_name_plural': '操作历史',
                'db_table': 'orcl_cz_ls',
            },
        ),
    ]
