# Generated by Django 3.2.2 on 2021-05-07 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orcl', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcl_cz_ls',
            name='czr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.bankaccount', verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='orcl_cz',
            name='orcl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orcl.orcl_ljcs', verbose_name='连接的库'),
        ),
    ]
