# Generated by Django 3.1.7 on 2021-04-21 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0003_bankaccount_bankdepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.bankdepartment',
                                    verbose_name='所属银行部门'),
        ),
    ]
