# Generated by Django 3.2.2 on 2021-05-07 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='回复人'),
        ),
        migrations.AddField(
            model_name='reply',
            name='forWhichGuestbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chats.guestbook', verbose_name='所属的留言'),
        ),
        migrations.AddField(
            model_name='guestbook',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='发言人'),
        ),
    ]
